/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 8ball.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/8ball.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Bone} />
          <group name="Ball001">
            <skinnedMesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.White} skeleton={nodes.Sphere002.skeleton} />
            <skinnedMesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials.Black} skeleton={nodes.Sphere002_1.skeleton} />
            <skinnedMesh name="Sphere002_2" geometry={nodes.Sphere002_2.geometry} material={materials.Blue} skeleton={nodes.Sphere002_2.skeleton} />
          </group>
          <skinnedMesh name="Text001" geometry={nodes.Text001.geometry} material={materials.Black} skeleton={nodes.Text001.skeleton} />
        </group>
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0, 1, 0]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/8ball.glb')
